---
# Configure the webservers.
- name: Configure webservers
  hosts: webservers
  vars_files:
    - vars/packages.yml 
    - vars/user_groups.yml
    - vars/users.yml

  tasks:
    # Manage user groups and users
    - name: Configure user accounts and groups
      include_tasks: tasks/user_management.yml

    # Install the packages and start the related services.
    - name: Include the environment task file and set the variables
      include_tasks: tasks/environment.yml
      vars:
        package: "{{ item.name }}"
        service: "{{ item.service }}"
      loop: "{{ packages }}"

    # Check the status of the services
    - name: Verify service status
      include_tasks: tasks/verify_services.yml
      vars:
        service: "{{ item.service }}"
      loop: "{{ packages }}"

    # Open the listed ports in firewalld.
    - name: Open the firewall ports
      include_tasks: tasks/firewall.yml
      vars:
        rule:
          - http
          - https

    # Create the index
    - name: Create web index
      include_tasks: tasks/web_content.yml

# Import and run the tests
- name: Run tests
  import_playbook: test.yml
