# main.yml
# This playbook coordinates the automation.
# Most customization should be done within the tasks or vars
---
# Configure the webservers.
- name: Configure webservers
  hosts: webservers
  vars_files:
    - vars/packages.yml 
    - vars/user_groups.yml
    - vars/users.yml
    - vars/firewall_rules.yml

  tasks:
    # Manage user groups and users
    - name: Configure user accounts and groups
      include_tasks: tasks/user_management.yml

    # Install packages and start related services.
    - name: Include the environment task file and set the variables
      include_tasks: tasks/environment.yml
      vars:
        package: "{{ item.name }}"
        service: "{{ item.service }}"
      loop: "{{ packages }}"

    # Check the status of the services, restarting the service if necessary
    - name: Verify service status
      include_tasks: tasks/verify_services.yml
      vars:
        service: "{{ item.service }}"
      loop: "{{ packages }}"

    # Open the listed ports in firewalld.
    - name: Open the firewall ports
      include_tasks: tasks/firewall.yml
      vars:
        rule: "{{ item.name }}"
      loop: "{{ rules }}"

    # Deploy web content for testing.
    - name: Create web index
      include_tasks: tasks/web_content.yml

# Import and run the tests
- name: Run tests
  import_playbook: plays/test.yml
