# tasks/verify_services.yml
# This file verifies system services and restarts them if necessary.
---
# I considered making this a test playbook, however, I think it's more suitable
# as a task since there could be side-effects of running. Where I believe the
# test playbooks should be side-effect free.
#
# Use systemctl is-active to check if the service is running.
- name: Verify and recover {{ service }} if needed
  block:
    # Check if the service is running
    - name: Verify service is running
      ansible.builtin.command: systemctl is-active {{ service }}
      register: service_check
      changed_when: false
      # Using .stdout != "active" here since it's more readable but using
      # .rc != 0 could achieve the same thing.
      failed_when: service_check.stdout != "active"

  rescue:
    - name: Service {{ service }} failed check - attempting to restart
      ansible.builtin.debug:
        msg: "Service {{ service }} is not running. Attempting a restart..."

    # If the service wasn't running, try to restart it.
    - name: Restart {{ service }}
      ansible.builtin.service:
        name: "{{ service }}"
        state: restarted

    # Check if restarting made it run.
    - name: Verify {{ service }} after restart
      ansible.builtin.command: systemctl is-active {{ service }}
      register: restart_check
      changed_when: false
      failed_when: false

    # Fail with a clear error if the service won't start.
    - name: Report final error status
      ansible.builtin.fail:
        msg: "ERROR: Attempts to start {{ service }} have failed!"
      # Using .stdout != "active" here since it's more readable but using
      # .rc != 0 could achieve the same thing.
      when: restart_check.stdout != "active"
