# tasks/web_content.yml
# This file creates a simple index file for testing web services.
---
- name: Create default index.html file
  ansible.builtin.copy:
    content: "Welcome to {{ ansible_hostname }} web server"
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'
