---
- name: Test web service
  hosts: workstation
  become: false
  tasks:
    - name: Connect to internet web server
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        status_code: 200
